name: CI Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
      - ready_for_review
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: student_management
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pgsql, pdo_pgsql, zip, bcmath, apcu
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          composer install
          npm install

      - name: Setup Environment
        run: |
          cp .env.example .env
          php artisan key:generate
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              break
            fi
            sleep 2
          done

      - name: Run migrations
        run: php artisan migrate:fresh

      - name: Build the Front-End
        run: npm run build

      - name: Run Laravel tests
        run: npx concurrently -c "composer run dev" "php artisan test --testsuite=Feature"
